name: "GetIntegrityAPI Proof of Publish"
description: "Generate a verifiable publish receipt for CI/CD releases"

inputs:
  api_key:
    description: "GetIntegrityAPI API key"
    required: true

outputs:
  proof_id:
    description: "Generated proof ID"
    value: ${{ steps.publish.outputs.proof_id }}
  receipt_url:
    description: "Public verification URL"
    value: ${{ steps.publish.outputs.receipt_url }}
  receipt_sha256:
    description: "SHA256 of receipt.json"
    value: ${{ steps.publish.outputs.receipt_sha256 }}
  receipt_pdf_path:
    description: "Path to generated receipt.pdf"
    value: ${{ steps.publish.outputs.receipt_pdf_path }}

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci || npm install

    - name: Run publish proof
      id: publish
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GI_API_KEY: ${{ inputs.api_key }}
      run: node index.js
