name: "GetIntegrityAPI Proof of Publish"
description: "Generate a verifiable publish receipt for CI/CD releases"

inputs:
  api_key:
    description: "GetIntegrityAPI API key"
    required: true
  workspace:
    description: "GitHub workspace path"
    required: true

outputs:
  proof_id:
    description: "Generated proof ID"
  receipt_url:
    description: "Public verification URL"
  receipt_sha256:
    description: "SHA256 hash of receipt"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Run publish proof
      run: node index.js
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GI_API_KEY: ${{ inputs.api_key }}
        GI_WORKSPACE: ${{ inputs.workspace }}
